### ISSUE TITLE
BOM Quantities appear incorrect

### ISSUE THREAD

**Issue by SteveGuidi** [lodefmode/moviecart#1]
The [BOM](https://github.com/lodefmode/moviecart/blob/main/circuit/Bom_8238251.csv) shows the quantities of each item increasing sequentially from 1 to 9.  Do we need 6 PIC microcontrollers for this project? :)

**Comment by lodefmode** [comment]
Hi. That's weird.
Those are likely just the increasing line numbers.
Just one of each thing basically! :)

I'll check it out.

Cheers.
Rob

**Comment by lodefmode** [comment]
I've added a new BOM with correct quantities.
They're all singles, except for some 0.1 uF caps, of which there are 3.

9422f38e3788e76c99cf78e0cc6214
