### ISSUE TITLE
broken crop in GUI

### ISSUE THREAD

**Issue by andrew-davie** [lodefmode/moviecart#12]
Loaded the crop tab, then clicked in the visual crop box window. Held button and moved mouse left. Crop changed to -0.4, etc, and I no longer have any ability to move the crop box, and the values are set to read only. So it's broken!  Image shows state where I cannot modify crop values.  I really dislike the enforcement of read-only on values I may want to change manually.

<img width="912" alt="Screenshot 2023-12-13 at 1 43 21 pm" src="https://github.com/lodefmode/moviecart/assets/16424075/29c65b24-d8a0-4bc1-9d2c-2e4e0436b4d5">

**Comment by lodefmode** [comment]
You can always press the 'Reset Crop' button, however latest is now has editable crop fields again.
Fix #81e4da7d79cc6d84c35776ca27ed072c797e86d8
